export const userCardContent = [
  {
    iconName: "usersIcon",
    cardName: "Users",
    cardNumber: "3000",
    iconBackground: "#fce8ff",
  },
  {
    iconName: "activeUsers",
    cardName: "Active Users",
    cardNumber: "2,453",
    iconBackground: "#eee8ff",
  },
  {
    iconName: "loan",
    cardName: "Users with Loans",
    cardNumber: "12,343",
    iconBackground: "#feefec",
  },
  {
    iconName: "userSavings",
    cardName: "Users With Savings",
    cardNumber: "102,243",
    iconBackground: "#ffebf0",
  },
];

export const usersMockData = [
  {
    organization: "Lendsqr",
    username: "Adedeji",
    email: "adedeji@lendqr.com",
    phoneNumber: "07049011040",
    dateJoined: "May 15, 2020: 10:00AM",
    status: "Inactive",
  },
  {
    organization: "Lendsqr",
    username: "John Doe",
    email: "johndoe@lendqr.com",
    phoneNumber: "08012345678",
    dateJoined: "June 20, 2021: 09:30AM",
    status: "Active",
  },
  {
    organization: "TechCorp",
    username: "Alice Johnson",
    email: "alice@techcorp.com",
    phoneNumber: "09098765432",
    dateJoined: "March 5, 2019: 02:15PM",
    status: "Active",
  },
  {
    organization: "FinancePro",
    username: "Bob Smith",
    email: "bob@financepro.com",
    phoneNumber: "08123456789",
    dateJoined: "November 12, 2018: 04:45PM",
    status: "Inactive",
  },
  {
    organization: "Lendsqr",
    username: "Emily Davis",
    email: "emily@lendqr.com",
    phoneNumber: "07011223344",
    dateJoined: "August 3, 2022: 11:20AM",
    status: "Active",
  },
  {
    organization: "TechCorp",
    username: "David Wilson",
    email: "david@techcorp.com",
    phoneNumber: "08055556666",
    dateJoined: "December 19, 2021: 03:10PM",
    status: "Pending",
  },
  {
    organization: "Lendsqr",
    username: "Emily Davis",
    email: "emily@lendqr.com",
    phoneNumber: "07011223344",
    dateJoined: "August 3, 2022: 11:20AM",
    status: "Active",
  },
  {
    organization: "TechCorp",
    username: "David Wilson",
    email: "david@techcorp.com",
    phoneNumber: "08055556666",
    dateJoined: "December 19, 2021: 03:10PM",
    status: "Inactive",
  },
];
